---
tomcat_version: v7.0.77
apache_url: http://apache.stu.edu.tw
tomcat_download_url: "{{apache_url}}/tomcat/tomcat-7/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.tar.gz"
tomcat_install_dir: /opt/tomcat
# Name of service
tomcat_service: tomcat_standalone
# User that will run tomcat
tomcat_user: tomcat
tomcat_password:  tomcat
tomcat_http_port: "8080"
tomcat_shutdown_port: "8005"
manager_user: manager-gui
manager_password: managersecret
tomcat_uid: '500' 
